name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request_target:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Grunt
        run: npm install -g grunt-cli

      - name: Install Node Dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Test
        if: ${{ github.repository != 'dafreels/metalus-api' }}
        run: grunt test:api

      - name: Build
        if: ${{ github.repository == 'dafreels/metalus-api' || github.event_name != 'pull_request_target'}}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: grunt build
