name: PR

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Build with tests
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Grunt
        run: npm install -g grunt-cli

      - name: Install Node Dependencies
        run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Test
        run: grunt test:api
